# docker-compose.prod.yml
services:
  app:       { volumes: !override [ storage_data:/var/www/dzsowda/storage ] }
  queue:     { volumes: !override [ storage_data:/var/www/dzsowda/storage ] }
  reverb:    { volumes: !override [ storage_data:/var/www/dzsowda/storage ] }
  scheduler: { volumes: !override [ storage_data:/var/www/dzsowda/storage ] }
  artisan:   { volumes: !override [ storage_data:/var/www/dzsowda/storage ] }
  nginx:     { volumes: !override [ storage_data:/var/www/dzsowda/storage:ro ] }
  node:      {
    volumes: !override [ storage_data:/var/www/dzsowda ],
    command: sh -c "npm ci --omit=dev && npm run build"
    }

volumes:
  storage_data:
